# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Smart Voting Simulator
email: smartvotingsimulator1@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simulator for voting methods - so you can understand how voting methods work
  for making group decisions. The best voting methods are responsive to all parts
  of the group and can even work when voters use strategies.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://paretomansmartvotesim.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: paretoman1
github_username:  paretoman
author:
  name: Paretoman
  email: smartvotingsimulator1@gmail.com
minima:
  social_links:
    github: Paretoman
    twitter: Paretoman1
    youtube_channel: UCrwpT8YjxePjH0RxSCwbTlQ
    youtube_channel_name: Paretoman
github: [metadata] # make warning go away # https://github.com/github/pages-gem/issues/399

# # Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dev/